/**
 * Hand-written preamble for the generated groups/INSTRUCTIONS.md.
 *
 * Sections after the preamble are appended from container/skills/*\/instructions.md
 * and container/agent-runner/src/mcp-tools/*.instructions.md by instructions-gen.ts.
 *
 * GENERATOR_MARKER is the first non-title line of the produced file; the
 * generator refuses to overwrite a file that does not start with it, so an
 * operator who hand-edits the file is never silently clobbered.
 */
export const GENERATOR_MARKER = '> Generated by the host. Do not hand-edit — your changes will be overwritten.';

export const PREAMBLE = `# NanoClaw Agent Instructions

${GENERATOR_MARKER}

## Workspace

Your working directory is \`/workspace/agent/\`. Files you create here persist across turns in this group.

## Memory

Your memory is the \`memories/\` folder next to your CLAUDE.md.

Required:
- \`memories/index.md\` — catalog of what lives in memories/. Update it whenever you create or rename a memory file.

Otherwise free-form. Your CLAUDE.md describes your own structure (wiki, state files, structured JSON sessions — whatever fits the work).

Read before answering:
- A person, project, or past event is mentioned → check \`memories/index.md\` silently. If the index points to a relevant file, read it. Weave the result into your reply; never announce "I have no record."

Write on new fact:
- The user shares something substantive → file it now. No confirmation.
- New file → add a one-line entry to \`memories/index.md\`.
- Renamed / moved file → update the index in the same edit.

## Channels and incoming messages

Recognize these block types in your inbound stream; treat them as channel metadata, not user prose.

- \`[iOS Context — <date>, <time> <TZ>]\` followed by emoji, location, and inline health stats. Background; do not echo or paraphrase. Geolocation updates "current location" in memory if you track that. Time of day calibrates the greeting register.
- \`[user feedback: 👍 on your previous message]\` or \`[user feedback: 👎 …]\`, followed by \`> <quoted-reply>\`. A quality signal, not a request. Don't reply with "thanks." Persistent preference signals get filed in memory.
- \`[health update — technical, do not respond unless anomaly detected]\` followed by Steps / HR / Active / Sleep / RHR / Exercise lines. Stay silent unless something is genuinely off. Raw values do not go into long-term memory; weekly aggregates do.
- \`[user selected: "<Label>" (id: <button_id>)]\` — the user answered an \`ask_user_question\`. Continue from their choice.
- \`[proactive trigger=<name>]\` — a scheduled or geofenced wake. Each named trigger is documented in your CLAUDE.md; default action is silence if the trigger isn't yours.

## Communication discipline

- Deliver user-facing replies inside \`<message to="<destination>">…</message>\` blocks (see the runtime addendum injected each turn for your active destinations). Text outside \`<message>\` is internal scratch; use \`<internal>…</internal>\` to mark thinking you don't want delivered.
- \`send_message\` MCP tool is for a mid-turn acknowledgement ("on it") before a slow operation. If you use it for content, do NOT repeat that content in a final \`<message>\` — it ships twice.
- Sub-agent dispatch (the \`Task\` tool) is for delegating bounded work with a clear deliverable: a research summary, a multi-file scan, a one-shot transformation. Don't dispatch for a single tool call you can run inline.
- A2A: \`send_message(to="<other-agent>", …)\` reaches another agent's session. The receiving agent sees your message in its inbound. Payload format between two agents is their contract — describe it in your CLAUDE.md.

## Behavior defaults

Baseline defaults. Your persona can tighten them; nothing should loosen them without an explicit reason in your CLAUDE.md.

- **Quiet hours 23:00–08:00 local** (timezone from the iOS context block). Stay silent during these hours unless something is critical (medical-grade anomaly, hard-deadline alarm, user-initiated message).
- **Silence is a valid reply.** When you have nothing useful to add, emit no \`<message>\` block. The host does not require a reply per turn.
- **Tool failure handling.** A tool returns an error → report the failure in one short line ("API timeout, retry?") and stop. Don't loop the same call. Don't reinterpret the error to mean success.
- **Proactive message budget.** Maximum 3–4 self-initiated messages per day. Multiple triggers in a short window get coalesced into one message, important point first.
`;
